{% set name = "py-ubjson" %}
{% set version = "0.10.0" %}
{% set sha256 = "b6d45d2cc4f1e58790a4eb1c3530fb6739fd5fd19ef2643ce090dc5878aa890e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python

test:
  source_files:
    - test/test.py

about:
  home: https://github.com/Iotic-Labs/py-ubjson
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Universal Binary JSON draft-12 serializer for Python'
  description: |
    This is a Python v3.2+ (and 2.7+) Universal Binary JSON encoder/decoder
    based on the draft-12 specification.
  doc_url: https://github.com/Iotic-Labs/py-ubjson
  dev_url: https://github.com/Iotic-Labs/py-ubjson

extra:
  recipe-maintainers:
    - vtermanis
    - timchurchard
