{% set version = "0.14.0" %}

package:
  name: py-ubjson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/py-ubjson/py-ubjson-{{ version }}.tar.gz
  sha256: f742c87bccc8653329d3f79b8b3f40d44d11d17cce7f6d7025a73c52ebf91c66

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - test/test.py

about:
  home: https://github.com/Iotic-Labs/py-ubjson
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Universal Binary JSON draft-12 serializer for Python'
  description: |
    This is a Python v3.2+ (and 2.7+) Universal Binary JSON encoder/decoder
    based on the draft-12 specification.
  doc_url: https://github.com/Iotic-Labs/py-ubjson
  dev_url: https://github.com/Iotic-Labs/py-ubjson

extra:
  recipe-maintainers:
    - vtermanis
    - timchurchard
