travis:
  secure:
    BINSTAR_TOKEN: DuDKpHvRg7seoZpursjMHzgtCVKsW//qsrz4YqAav912TyHd7ETPJWo7lBXJfvq+hCAkH89z6neTv3LvIyo81co3Xm8vC9OLSS/+oGIZRHiG/pUEFlBotMKU56It2YWLQN+bCeVCFFDevh9JbA1fNNCCLpAOVBnHEyc6M1hmFm+CWKmXPOXd1VE7dtk0snYHH+P/ezdNemOFNGht1LhBYAIEdCDdCVk3hUP0JkeDa4RbBlP1FQ0wQZ3LN/F13P4hcDE/eaNsH7co+gNPyf1I+UEMj20ElDzZC6rkxVqbufofq9pBeCOj+5g83k3ok40Yf3XXDW8kqbfNYxjVKaUYnR/f+qXCa0a8eVEv1llzXGhUbvKeTqMJit0tlQ4DEzb8jk7OgpzJ5qL+rSaUq4z89CZu93H88x5ztmpdyLCh+dsbG06YHFfahn0IMbgO8g+bYCFiejVE4z0GyVBh6CCMwF5bsp67LBIAekH/TWOstuPklXTVtDum0iOwuuBIov04+H7XkHY+OGmQ0bYTvLA4epY8jffasCLkZliI9IoqLsnyv9h4fzsotD82n4wtM8WfzFJBqKFuLG4G7T7koJ1YEzcXh4oqm7E0f+j6pE/xiKvGT67tyNf/mWE2rEnXGJGHP85kPg/8kWq4g5U2JHxBb9gkDIyTgcKUUIqRv7vS8vg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
