travis:
  secure:
    BINSTAR_TOKEN: BOXWJSh4+zijNwmJWznX9jAzATsTz8kmcEpKTE0/MKH3vDy8PNA0QcC6gsf5tc9fPun5Ts+A7LTXkjJLgJZk626WhSg9GNdcHPLgTptzY1CG0MRMFLEoBGvvHrvhZ2qs+WpkPr8I77DYXWhMSt28+cZJjooMhZzkDRDbCUCDZ7obxCxUYiOlUonT82j6QB1bqRwXQZyhd4TVIc3Sz0ektC/8TaZHpyF4iUlMYrjLMhzg1/rgxmIKyOjhVGTiXu7TmJmMoQ4G7IbZp195FWwUf5mCYOB8OCR+y8lNDyNS3+eR3DvisY5nkxiF1P2P4qrRJeeU9J5iyCiVfIZSU5aNMnFMXg+VivZXuZMydq2+dqZPWJaAx8HsBl2fokuj4V7oYviVEtpBfXUkUyG+UJ4MhGY8ScNebueVOb8YRU8Qg9ClPUxMH2+hVaIfFkhs0yB3JwHEN5AkBW1EdNX9FL+eWUP2+ikSUuKxydJoC+sSR/O+G6ZHpu6fIhekfdoy2Ooa/jPr9C+sxXH/MC9qolyXdibNOpfGoO7FSWhFH05twML7pQHBT5/rJ/Wzcg4VW4yQUNIFokst1JjU7upGOwumBenbOsMedAb/0U0JNGWTzuvPd1e0YUSpOs442sh13nG4g4veKVOPdjT/zRrU03yIrwH5XvH2jLexJf5Re9pZBzM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
